modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0"

[[mods]]
modId = "immersiveconvergence"
version = "${version}"
displayName = "Immersive Convergence"
description = "API for Immersive Engineering addons."
authors = "tgstyle"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/immersive-convergence"
logoFile = "IClogo.png"
credits = "tgstyle"

[[dependencies.immersiveconvergence]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.immersiveconvergence]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"